@startuml
class umlparser.ExampleClass {
  - foo : int
  - bar : java.lang.String
  + <init>(int, java.lang.String) : void
  + getFoo() : int
  + setFoo(int) : void
  + getBar() : java.lang.String
  + setBar(java.lang.String) : void
}
@enduml
