@startuml
class umlparser.MethodInfo {
  - name : java.lang.String
  - returnType : java.lang.String
  - parameterTypes : java.util.List
  - access : int
  + <init>(java.lang.String, java.lang.String, java.util.List, int) : void
  + getName() : java.lang.String
  + getReturnType() : java.lang.String
  + getParameterTypes() : java.util.List
  + getAccess() : int
}
@enduml
